# version: '3'
# services:
#   web:
#     build: .
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#   db:
#     image: mysql-custom:latest
#     environment:
#       MYSQL_ALLOW_EMPTY_PASSWORD: yes
#       MYSQL_DATABASE: challenge48h
